CREATE FUNCTION [dbo].[SplitInt]
(
	@list VARCHAR(MAX),
	@delimiter VARCHAR(10)
)
RETURNS TABLE
AS
	RETURN (SELECT TRY_CAST(value AS INT) AS Value
			FROM STRING_SPLIT(@list, @delimiter)
			WHERE TRY_CAST(value AS INT) IS NOT NULL);