CREATE FUNCTION [dbo].[SplitBigInt]
(
	@list VARCHAR(MAX),
	@delimiter VARCHAR(10)
)
RETURNS TABLE
AS
	RETURN (SELECT TRY_CAST(value AS BIGINT) AS Value
			FROM STRING_SPLIT(@list, @delimiter)
			WHERE TRY_CAST(value AS BIGINT) IS NOT NULL);