CREATE PROCEDURE [dbo].[sp_Email_Delete]
    @EmailId BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[Email]
    WHERE EmailId = @EmailId;

    SELECT CAST(CASE WHEN @@ROWCOUNT > 0 THEN 1 ELSE 0 END AS BIT);
END