CREATE PROCEDURE [dbo].[sp_User_Delete]
    @UserId BIGINT
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM [dbo].[User]
    WHERE UserId = @UserId;

    SELECT CAST(CASE WHEN @@ROWCOUNT > 0 THEN 1 ELSE 0 END AS BIT);
END